restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py --cluster '{cookiecutter.cluster_name}' --status_attempts 20"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
